### PR TITLE
Add IrcConnection::connectionCount to count established [WIP]

### PR DESCRIPTION
**Pull request by Thaodan**
See #69

### CODE REVIEW

**Comment by jpnurmi** [comment]
Thanks! :+1:

Should it reset the counter when the connection is explicitly closed?

**Comment by Thaodan** [comment]
Hm could be. My idea behind it was to collect amount of times a connection was established to decide if the channel topic should be shown again or the connection should be closed if the connection accours to fast in a given amount of time.

**Comment by jpnurmi** [comment]
I'm wondering because a desktop client can run in the background long periods without a reboot. I wouldn't expect the counter to tell how many times the client has reconnected over the course of the whole runtime history, if I have manually disconnected and connected in between. ;)

**Comment by Thaodan** [comment]
No idea but is that bad?
We could reset the counter when a 
manual disconnect is issued sure.

**Pull request merged**
