### PR TITLE
Restore Qt 4 compatibility

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by Thaodan** [comment]
Who uses that still?

**Comment by jpnurmi** [comment]
> Who uses that still?

The same people who use Debian stable? :grin:

No, but seriously, Qt 4 is not that awful for "backend" stuff, actually. It's less bloated than Qt 5 and doesn't force a platform plugin on you even if you'd use the basic QtGui classes, such as QColor & friends (like IrcUtil does). And Qt 4 doesn't prevent you from using modern C++, which Qt 5 is shoveling down your throat anyway by deprecating as much overlap with std::xxx as possible.

**Comment by jpnurmi** [comment]
The idea is to do one more release in the 3.x series, whilst keeping backward compatibility. The next major version can start depending on Qt 5...

**Comment by SlySven** [comment]
🤔 Apparently Qt ended standard support for Qt 4.8.7 LTS in December 2015...! https://www.qt.io/blog/2015/05/26/qt-4-8-7-released

**Pull request merged**
